export type RepoGroupName = "type-defs" | "usage";

export interface RepoSpec {
  id: string;
  group: RepoGroupName;
  url: string;
  checkoutDir: string;
  extractPath?: string;
}

export const REPO_MANIFEST: RepoSpec[] = [
  // Group 1: canonical type-definition sources.
  {
    id: "native-browser-types",
    group: "type-defs",
    url: "https://github.com/microsoft/TypeScript.git",
    checkoutDir: "data/repos/type-defs/TypeScript",
    extractPath: "src/lib",
  },
  {
    id: "react-types",
    group: "type-defs",
    url: "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
    checkoutDir: "data/repos/type-defs/DefinitelyTyped",
    extractPath: "types/react",
  },
  {
    id: "react-dom-types",
    group: "type-defs",
    url: "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
    checkoutDir: "data/repos/type-defs/DefinitelyTyped",
    extractPath: "types/react-dom",
  },
  {
    id: "astro-types",
    group: "type-defs",
    url: "https://github.com/withastro/astro.git",
    checkoutDir: "data/repos/type-defs/astro",
    extractPath: "packages/astro/types",
  },
  {
    id: "astro-language-tools-types",
    group: "type-defs",
    url: "https://github.com/withastro/language-tools.git",
    checkoutDir: "data/repos/type-defs/astro-language-tools",
  },
  {
    id: "tanstack-query-types",
    group: "type-defs",
    url: "https://github.com/TanStack/query.git",
    checkoutDir: "data/repos/type-defs/tanstack-query",
    extractPath: "packages",
  },
  {
    id: "tanstack-router-types",
    group: "type-defs",
    url: "https://github.com/TanStack/router.git",
    checkoutDir: "data/repos/type-defs/tanstack-router",
    extractPath: "packages",
  },
  {
    id: "native-dom-lib-generator",
    group: "type-defs",
    url: "https://github.com/microsoft/TypeScript-DOM-lib-generator.git",
    checkoutDir: "data/repos/type-defs/TypeScript-DOM-lib-generator",
  },
  {
    id: "lit-web-components-types",
    group: "type-defs",
    url: "https://github.com/lit/lit.git",
    checkoutDir: "data/repos/type-defs/lit",
    extractPath: "packages",
  },
  {
    id: "fast-web-components-types",
    group: "type-defs",
    url: "https://github.com/microsoft/fast.git",
    checkoutDir: "data/repos/type-defs/fast",
    extractPath: "packages",
  },

  // Group 2: usage repositories (component libraries) that use at least one
  // ecosystem from group 1: browser native types, React, Astro, TanStack.
  {
    id: "radix-primitives",
    group: "usage",
    url: "https://github.com/radix-ui/primitives.git",
    checkoutDir: "data/repos/usage/radix-primitives",
  },
  {
    id: "react-spectrum",
    group: "usage",
    url: "https://github.com/adobe/react-spectrum.git",
    checkoutDir: "data/repos/usage/react-spectrum",
  },
  {
    id: "material-ui",
    group: "usage",
    url: "https://github.com/mui/material-ui.git",
    checkoutDir: "data/repos/usage/material-ui",
  },
  {
    id: "chakra-ui",
    group: "usage",
    url: "https://github.com/chakra-ui/chakra-ui.git",
    checkoutDir: "data/repos/usage/chakra-ui",
  },
  {
    id: "ant-design",
    group: "usage",
    url: "https://github.com/ant-design/ant-design.git",
    checkoutDir: "data/repos/usage/ant-design",
  },
  {
    id: "headlessui",
    group: "usage",
    url: "https://github.com/tailwindlabs/headlessui.git",
    checkoutDir: "data/repos/usage/headlessui",
  },
  {
    id: "reach-ui",
    group: "usage",
    url: "https://github.com/reach/reach-ui.git",
    checkoutDir: "data/repos/usage/reach-ui",
  },
  {
    id: "mantine",
    group: "usage",
    url: "https://github.com/mantinedev/mantine.git",
    checkoutDir: "data/repos/usage/mantine",
  },
  {
    id: "react-bootstrap",
    group: "usage",
    url: "https://github.com/react-bootstrap/react-bootstrap.git",
    checkoutDir: "data/repos/usage/react-bootstrap",
  },
  {
    id: "primer-react",
    group: "usage",
    url: "https://github.com/primer/react.git",
    checkoutDir: "data/repos/usage/primer-react",
  },
  {
    id: "semantic-ui-react",
    group: "usage",
    url: "https://github.com/Semantic-Org/Semantic-UI-React.git",
    checkoutDir: "data/repos/usage/semantic-ui-react",
  },
  {
    id: "shadcn-ui",
    group: "usage",
    url: "https://github.com/shadcn-ui/ui.git",
    checkoutDir: "data/repos/usage/shadcn-ui",
  },
  {
    id: "react-router",
    group: "usage",
    url: "https://github.com/remix-run/react-router.git",
    checkoutDir: "data/repos/usage/react-router",
  },
  {
    id: "t3-app",
    group: "usage",
    url: "https://github.com/t3-oss/create-t3-app.git",
    checkoutDir: "data/repos/usage/create-t3-app",
  },
  {
    id: "tanstack-start",
    group: "usage",
    url: "https://github.com/TanStack/router.git",
    checkoutDir: "data/repos/usage/tanstack-router-usage",
    extractPath: "examples",
  },
  {
    id: "starlight",
    group: "usage",
    url: "https://github.com/withastro/starlight.git",
    checkoutDir: "data/repos/usage/starlight",
  },
  {
    id: "astro-icon",
    group: "usage",
    url: "https://github.com/natemoo-re/astro-icon.git",
    checkoutDir: "data/repos/usage/astro-icon",
  },
  {
    id: "lit",
    group: "usage",
    url: "https://github.com/lit/lit.git",
    checkoutDir: "data/repos/usage/lit",
  },
  {
    id: "shoelace",
    group: "usage",
    url: "https://github.com/shoelace-style/shoelace.git",
    checkoutDir: "data/repos/usage/shoelace",
  },
  {
    id: "ionic-framework",
    group: "usage",
    url: "https://github.com/ionic-team/ionic-framework.git",
    checkoutDir: "data/repos/usage/ionic-framework",
  },
  {
    id: "fast",
    group: "usage",
    url: "https://github.com/microsoft/fast.git",
    checkoutDir: "data/repos/usage/fast",
  },
  {
    id: "react-select",
    group: "usage",
    url: "https://github.com/JedWatson/react-select.git",
    checkoutDir: "data/repos/usage/react-select",
  },
  {
    id: "react-day-picker",
    group: "usage",
    url: "https://github.com/gpbl/react-day-picker.git",
    checkoutDir: "data/repos/usage/react-day-picker",
  },
  {
    id: "react-window",
    group: "usage",
    url: "https://github.com/bvaughn/react-window.git",
    checkoutDir: "data/repos/usage/react-window",
  },
  {
    id: "floating-ui",
    group: "usage",
    url: "https://github.com/floating-ui/floating-ui.git",
    checkoutDir: "data/repos/usage/floating-ui",
  },
  {
    id: "ariakit",
    group: "usage",
    url: "https://github.com/ariakit/ariakit.git",
    checkoutDir: "data/repos/usage/ariakit",
  },
  {
    id: "dnd-kit",
    group: "usage",
    url: "https://github.com/clauderic/dnd-kit.git",
    checkoutDir: "data/repos/usage/dnd-kit",
  },
  {
    id: "react-dnd",
    group: "usage",
    url: "https://github.com/react-dnd/react-dnd.git",
    checkoutDir: "data/repos/usage/react-dnd",
  },
  {
    id: "react-admin",
    group: "usage",
    url: "https://github.com/marmelab/react-admin.git",
    checkoutDir: "data/repos/usage/react-admin",
  },
  {
    id: "tamagui",
    group: "usage",
    url: "https://github.com/tamagui/tamagui.git",
    checkoutDir: "data/repos/usage/tamagui",
  },
  {
    id: "blueprint",
    group: "usage",
    url: "https://github.com/palantir/blueprint.git",
    checkoutDir: "data/repos/usage/blueprint",
  },
  {
    id: "evergreen",
    group: "usage",
    url: "https://github.com/segmentio/evergreen.git",
    checkoutDir: "data/repos/usage/evergreen",
  },
  {
    id: "grommet",
    group: "usage",
    url: "https://github.com/grommet/grommet.git",
    checkoutDir: "data/repos/usage/grommet",
  },
  {
    id: "fluentui",
    group: "usage",
    url: "https://github.com/microsoft/fluentui.git",
    checkoutDir: "data/repos/usage/fluentui",
  },
  {
    id: "baseweb",
    group: "usage",
    url: "https://github.com/uber/baseweb.git",
    checkoutDir: "data/repos/usage/baseweb",
  },
  {
    id: "material-web",
    group: "usage",
    url: "https://github.com/material-components/material-web.git",
    checkoutDir: "data/repos/usage/material-web",
  },
  {
    id: "spectrum-web-components",
    group: "usage",
    url: "https://github.com/adobe/spectrum-web-components.git",
    checkoutDir: "data/repos/usage/spectrum-web-components",
  },
  {
    id: "vaadin-web-components",
    group: "usage",
    url: "https://github.com/vaadin/web-components.git",
    checkoutDir: "data/repos/usage/vaadin-web-components",
  },
  {
    id: "lion",
    group: "usage",
    url: "https://github.com/ing-bank/lion.git",
    checkoutDir: "data/repos/usage/lion",
  },
  {
    id: "ui5-webcomponents",
    group: "usage",
    url: "https://github.com/SAP/ui5-webcomponents.git",
    checkoutDir: "data/repos/usage/ui5-webcomponents",
  },
  {
    id: "react-hook-form",
    group: "usage",
    url: "https://github.com/react-hook-form/react-hook-form.git",
    checkoutDir: "data/repos/usage/react-hook-form",
  },
  {
    id: "formik",
    group: "usage",
    url: "https://github.com/jaredpalmer/formik.git",
    checkoutDir: "data/repos/usage/formik",
  },
  {
    id: "remirror",
    group: "usage",
    url: "https://github.com/remirror/remirror.git",
    checkoutDir: "data/repos/usage/remirror",
  },
  {
    id: "rsuite",
    group: "usage",
    url: "https://github.com/rsuite/rsuite.git",
    checkoutDir: "data/repos/usage/rsuite",
  },
  {
    id: "nextui",
    group: "usage",
    url: "https://github.com/nextui-org/nextui.git",
    checkoutDir: "data/repos/usage/nextui",
  },
  {
    id: "cmdk",
    group: "usage",
    url: "https://github.com/pacocoursey/cmdk.git",
    checkoutDir: "data/repos/usage/cmdk",
  },
  {
    id: "vaul",
    group: "usage",
    url: "https://github.com/emilkowalski/vaul.git",
    checkoutDir: "data/repos/usage/vaul",
  },
  {
    id: "react-dropzone",
    group: "usage",
    url: "https://github.com/react-dropzone/react-dropzone.git",
    checkoutDir: "data/repos/usage/react-dropzone",
  },
  {
    id: "react-grid-layout",
    group: "usage",
    url: "https://github.com/react-grid-layout/react-grid-layout.git",
    checkoutDir: "data/repos/usage/react-grid-layout",
  },
  {
    id: "react-modal",
    group: "usage",
    url: "https://github.com/reactjs/react-modal.git",
    checkoutDir: "data/repos/usage/react-modal",
  },
  {
    id: "downshift",
    group: "usage",
    url: "https://github.com/downshift-js/downshift.git",
    checkoutDir: "data/repos/usage/downshift",
  },
  {
    id: "react-tabs",
    group: "usage",
    url: "https://github.com/reactjs/react-tabs.git",
    checkoutDir: "data/repos/usage/react-tabs",
  },
  {
    id: "rc-select",
    group: "usage",
    url: "https://github.com/react-component/select.git",
    checkoutDir: "data/repos/usage/rc-select",
  },
  {
    id: "rc-tree",
    group: "usage",
    url: "https://github.com/react-component/tree.git",
    checkoutDir: "data/repos/usage/rc-tree",
  },
  {
    id: "rc-menu",
    group: "usage",
    url: "https://github.com/react-component/menu.git",
    checkoutDir: "data/repos/usage/rc-menu",
  },
  {
    id: "rc-trigger",
    group: "usage",
    url: "https://github.com/react-component/trigger.git",
    checkoutDir: "data/repos/usage/rc-trigger",
  },
  {
    id: "rc-field-form",
    group: "usage",
    url: "https://github.com/react-component/field-form.git",
    checkoutDir: "data/repos/usage/rc-field-form",
  },
  {
    id: "rc-dialog",
    group: "usage",
    url: "https://github.com/react-component/dialog.git",
    checkoutDir: "data/repos/usage/rc-dialog",
  },
  {
    id: "rc-upload",
    group: "usage",
    url: "https://github.com/react-component/upload.git",
    checkoutDir: "data/repos/usage/rc-upload",
  },
  {
    id: "react-toastify",
    group: "usage",
    url: "https://github.com/fkhadra/react-toastify.git",
    checkoutDir: "data/repos/usage/react-toastify",
  },
];
